package org.areslib.core.localization;

import com.pedropathing.drivetrain.Drivetrain;
import com.pedropathing.math.Vector;
import org.areslib.subsystems.drive.SwerveDriveSubsystem;

/**
 * A translation layer bridging Pedro Pathing's native drive outputs into ARESLib's {@link SwerveDriveSubsystem}.
 * <p>
 * This class inherits from Pedro's {@link Drivetrain} abstraction, but instead of sending power
 * directly to motors, it captures the geometric PID targets generated by the Pedro Follower and 
 * forwards them asynchronously to the ARES Swerve Drive system.
 */
public class AresPedroDrivetrain extends Drivetrain {

    private final SwerveDriveSubsystem driveSubsystem;
    /**
     * Constructs a new AresPedroDrivetrain.
     *
     * @param driveSubsystem The underlying ARES drivetrain that will physically actuate the robot.
     */
    public AresPedroDrivetrain(SwerveDriveSubsystem driveSubsystem) {
        super();
        this.driveSubsystem = driveSubsystem;
    }

    /**
     * Called continuously by Pedro Pathing's Follower state machine to update physical motor speeds.
     * <p>
     * Instead of applying direct hardware voltages, this implementation scales the translational
     * and rotational PID output vectors into simulated m/s and rad/s values that ARESlib's
     * kinematics solver expects.
     *
     * @param correctivePower  The corrective translation vector to stay on path.
     * @param headingPower     The rotational vector for heading correction.
     * @param pathingPower     The forward feedforward velocity vector.
     * @param robotHeading     The current rotation of the robot in radians.
     * @return Dummy zero-power array since hardware application happens asynchronously via the ARES framework.
     */
    @Override
    public double[] calculateDrive(Vector correctivePower, Vector headingPower, Vector pathingPower, double robotHeading) {
        try {
            double currentForward = 0.0;
            double currentStrafe = 0.0;
            double currentTurn = 0.0;

            if (driveSubsystem == null) {
                return new double[]{0, 0, 0, 0};
            }

            Vector combinedMovement = new Vector();
            if (correctivePower != null) combinedMovement = combinedMovement.plus(correctivePower);
            if (pathingPower != null) combinedMovement = combinedMovement.plus(pathingPower);
            
            // These are FIELD-CENTRIC outputs from Pedro.
            double forwardInput = combinedMovement.getXComponent();
            double strafeInput = combinedMovement.getYComponent();
            
            // To get turn power, we do the Pedro dot product trick used in CustomDrivetrain:
            double turnInput = 0.0;
            if (headingPower != null) {
                turnInput = headingPower.dot(new Vector(1, robotHeading));
            }

            // Rotate the field-centric drive vector by -heading to get robot-centric components
            double robotCentricX = forwardInput * Math.cos(-robotHeading) - strafeInput * Math.sin(-robotHeading);
            double robotCentricY = forwardInput * Math.sin(-robotHeading) + strafeInput * Math.cos(-robotHeading);
            
            // Note: Pedro typically outputs motor powers natively, but since we are simulating field-centric chassis speeds:
            // We will scale these raw PID outputs into approximate physical velocities for the simulator.
            currentForward = robotCentricX * 3.0; // Scaled up to represent roughly 3 m/s max
            currentStrafe = robotCentricY * 3.0;
            currentTurn = turnInput * 3.0; // Scaled up to represent roughly 3 rad/s max

            driveSubsystem.drive(currentForward, currentStrafe, currentTurn);
        } catch (Exception e) {
            System.err.println("CRASH IN ARES PEDRO DRIVETRAIN: " + e.getMessage());
            e.printStackTrace();
        }
        return new double[]{0, 0, 0, 0}; // Return unused power array

    }

    /** Unused in ARES configuration. Teleop handled by Commands. */
    @Override
    public void startTeleopDrive() {}

    /** Unused in ARES configuration. */
    @Override
    public void startTeleopDrive(boolean useVoltageCompensation) {}

    /**
     * Unused in ARES configuration.
     * {@link #calculateDrive} forwards signals automatically.
     */
    @Override
    public void runDrive(double[] powers) {
        // Unused directly, as calculateDrive drives the subsystem asynchronously
    }

    /** Stops all chassis movement immediately. */
    @Override
    public void breakFollowing() {
        driveSubsystem.drive(0, 0, 0);
    }

    /** Unused wrapper mapping back to tracking wheel internal state. */
    @Override
    public double xVelocity() { return 0; }

    /** Unused wrapper mapping back to tracking wheel internal state. */
    @Override
    public double yVelocity() { return 0; }

    /** Unused wrapper since constants are injected live via the Subsystem binding. */
    @Override
    public void updateConstants() {}

    /** Unused internal setter. */
    @Override
    public void setXVelocity(double xV) {}

    /** Unused internal setter. */
    @Override
    public void setYVelocity(double yV) {}

    /** 
     * Returns the live battery voltage for Pedro's internal voltage compensation.
     * <p>Reads from the {@link org.areslib.hardware.AresHardwareManager} brownout system.
     */
    @Override
    public double getVoltage() { return org.areslib.hardware.AresHardwareManager.getBatteryVoltage(); }

    /** Used by FTC Dashboard for graphical logging. */
    @Override
    public String debugString() { return "AresPedroSwerveBridge"; }
}
