package org.areslib.core.localization;

import com.pedropathing.drivetrain.Drivetrain;
import com.pedropathing.math.Vector;
import org.areslib.subsystems.drive.DriveSubsystem;

/**
 * A translation layer bridging Pedro Pathing's native drive outputs into ARESLib's {@link DriveSubsystem}.
 * <p>
 * This class inherits from Pedro's {@link Drivetrain} abstraction, but instead of sending power
 * directly to motors, it captures the geometric PID targets generated by the Pedro Follower and 
 * forwards them asynchronously to the ARES Swerve Drive system.
 */
public class AresPedroDrivetrain extends Drivetrain {

    private final DriveSubsystem driveSubsystem;
    
    // Internal state cache for logging/telemetry
    private double currentForward = 0.0;
    private double currentStrafe = 0.0;
    private double currentTurn = 0.0;

    /**
     * Constructs a new AresPedroDrivetrain.
     *
     * @param driveSubsystem The underlying ARES drivetrain that will physically actuate the robot.
     */
    public AresPedroDrivetrain(DriveSubsystem driveSubsystem) {
        super();
        this.driveSubsystem = driveSubsystem;
    }

    /**
     * Called continuously by Pedro Pathing's Follower state machine to update physical motor speeds.
     * <p>
     * Instead of applying direct hardware voltages, this implementation scales the translational
     * and rotational PID output vectors into simulated m/s and rad/s values that ARESlib's
     * kinematics solver expects.
     *
     * @param driveError    The current purely geometric drive error vector.
     * @param headingError  The current purely geometric heading error vector.
     * @param driveVector   The internal drive PID output computed by the follower.
     * @param headingVector The internal heading PID output computed by the follower.
     * @return Dummy zero-power array since hardware application happens asynchronously via the ARES framework.
     */
    @Override
    public double[] calculateDrive(Vector driveError, Vector headingError, Vector driveVector, double headingVector) {
        // Pedro Pathing calculates error vectors based on inches natively.
        // We will convert these into reasonable inputs for Swerve Drive kinematics.
        // ARESlib DriveSubsystem takes (forwardMetersPerSec, strafeMetersPerSec, turnRadPerSec)
        
        // Pedro Pathing calculates PID outputs internally and passes them via driveVector and headingVector.
        // driveError and headingError are the true geometric errors, NOT the control inputs.
        // We only want the control inputs (PID outputs).
        double forwardInput = driveVector.getXComponent();
        double strafeInput = driveVector.getYComponent();
        double turnInput = headingVector; 

        // Note: Pedro typically outputs motor powers natively, but since we are simulating field-centric chassis speeds:
        // We will scale these raw PID outputs into approximate physical velocities for the simulator.
        currentForward = forwardInput * 2.0; // Scaled up to represent roughly 2 m/s max
        currentStrafe = strafeInput * 2.0;
        currentTurn = turnInput * 2.0; // Scaled up to represent roughly 2 rad/s max

        driveSubsystem.drive(currentForward, currentStrafe, currentTurn);

        return new double[]{0, 0, 0, 0}; // Return unused power array
    }

    /** Unused in ARES configuration. Teleop handled by Commands. */
    @Override
    public void startTeleopDrive() {}

    /** Unused in ARES configuration. */
    @Override
    public void startTeleopDrive(boolean useVoltageCompensation) {}

    /**
     * Unused in ARES configuration.
     * {@link #calculateDrive} forwards signals automatically.
     */
    @Override
    public void runDrive(double[] powers) {
        // Unused directly, as calculateDrive drives the subsystem asynchronously
    }

    /** Stops all chassis movement immediately. */
    @Override
    public void breakFollowing() {
        driveSubsystem.drive(0, 0, 0);
    }

    /** Unused wrapper mapping back to tracking wheel internal state. */
    @Override
    public double xVelocity() { return 0; }

    /** Unused wrapper mapping back to tracking wheel internal state. */
    @Override
    public double yVelocity() { return 0; }

    /** Unused wrapper since constants are injected live via the Subsystem binding. */
    @Override
    public void updateConstants() {}

    /** Unused internal setter. */
    @Override
    public void setXVelocity(double xV) {}

    /** Unused internal setter. */
    @Override
    public void setYVelocity(double yV) {}

    /** 
     * Hardcoded default return for voltage compensation inside Pedro.
     * <p>ARESlib relies on hardware-level cached expansion hub voltage readings instead.
     */
    @Override
    public double getVoltage() { return 12.0; }

    /** Used by FTC Dashboard for graphical logging. */
    @Override
    public String debugString() { return "AresPedroSwerveBridge"; }
}
