import React, { useState } from 'react';
import { Plus, Trash2, Download, Copy, Check } from 'lucide-react';

interface SubsystemConfig {
  name: string;
  type: 'drivetrain' | 'mechanism' | 'vision' | 'sensor';
  motors: number;
  sensors: string[];
}

interface RobotConfig {
  teamName: string;
  driveType: 'mecanum' | 'swerve' | 'differential';
  subsystems: SubsystemConfig[];
}

const SUBSYSTEM_TYPES = [
  { value: 'drivetrain', label: 'Drivetrain', icon: '🚗' },
  { value: 'mechanism', label: 'Mechanism', icon: '⚙️' },
  { value: 'vision', label: 'Vision', icon: '👁️' },
  { value: 'sensor', label: 'Sensor', icon: '📡' },
];

const DRIVE_TYPES = [
  { value: 'mecanum', label: 'Mecanum Drive', description: 'Omni-directional, proven reliability' },
  { value: 'swerve', label: 'Swerve Drive', description: 'Maximum maneuverability, advanced' },
  { value: 'differential', label: 'Differential Drive', description: 'Simple, tank-style control' },
];

export default function ConfigVisualizer() {
  const [config, setConfig] = useState<RobotConfig>({
    teamName: '',
    driveType: 'mecanum',
    subsystems: [],
  });

  const [generatedCode, setGeneratedCode] = useState('');
  const [copied, setCopied] = useState(false);

  const addSubsystem = () => {
    setConfig({
      ...config,
      subsystems: [
        ...config.subsystems,
        {
          name: `subsystem${config.subsystems.length + 1}`,
          type: 'mechanism',
          motors: 1,
          sensors: [],
        },
      ],
    });
  };

  const updateSubsystem = (index: number, updates: Partial<SubsystemConfig>) => {
    const newSubsystems = [...config.subsystems];
    newSubsystems[index] = { ...newSubsystems[index], ...updates };
    setConfig({ ...config, subsystems: newSubsystems });
  };

  const removeSubsystem = (index: number) => {
    setConfig({
      ...config,
      subsystems: config.subsystems.filter((_, i) => i !== index),
    });
  };

  const generateCode = () => {
    let code = `// ${config.teamName || 'MyTeam'} Robot Configuration\n`;
    code += `// Generated by ARESLib Config Visualizer\n\n`;

    // Robot Container
    code += `public class RobotContainer {\n`;
    code += `    private final ${config.driveType}DriveSubsystem drive;\n`;

    config.subsystems.forEach(sub => {
      code += `    private final ${sub.name}Subsystem ${sub.name.toLowerCase()};\n`;
    });

    code += `\n    public RobotContainer() {\n`;
    code += `        // Initialize drivetrain\n`;
    code += `        drive = new ${config.driveType}DriveSubsystem(\n`;
    code += `            new DriveIOReal(hardwareMap)\n`;
    code += `        );\n\n`;

    config.subsystems.forEach(sub => {
      code += `        // Initialize ${sub.name}\n`;
      code += `        ${sub.name.toLowerCase()} = new ${sub.name}Subsystem(\n`;
      code += `            new ${sub.name}IOReal(hardwareMap)\n`;
      code += `        );\n\n`;
    });

    code += `        // Configure default commands\n`;
    code += `        drive.setDefaultCommand(new DefaultDriveCommand(\n`;
    code += `            drive,\n`;
    code += `            () -> driver.getLeftX(),\n`;
    code += `            () -> driver.getLeftY(),\n`;
    code += `            () -> driver.getRightX()\n`;
    code += `        ));\n`;
    code += `    }\n`;
    code += `}\n`;

    // Generate IO interface example
    code += `\n// Example IO Interface for first subsystem\n`;
    if (config.subsystems.length > 0) {
      const sub = config.subsystems[0];
      code += `public interface ${sub.name}IO {\n`;
      code += `    @AutoLog\n`;
      code += `    public static class ${sub.name}IOInputs {\n`;
      code += `        public double positionRadians = 0.0;\n`;
      code += `        public double velocityRadiansPerSec = 0.0;\n`;
      code += `        public double appliedVolts = 0.0;\n`;
      code += `    }\n\n`;
      code += `    void updateInputs(${sub.name}IOInputs inputs);\n`;
      code += `    void setVoltage(double volts);\n`;
      code += `}\n`;
    }

    setGeneratedCode(code);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="config-visualizer">
      <div className="config-panels">
        <div className="config-panel">
          <h3>Robot Configuration</h3>

          <div className="config-section">
            <label>Team Name</label>
            <input
              type="text"
              value={config.teamName}
              onChange={(e) => setConfig({ ...config, teamName: e.target.value })}
              placeholder="FTC Team 12345"
            />
          </div>

          <div className="config-section">
            <label>Drive Type</label>
            <div className="drive-type-selector">
              {DRIVE_TYPES.map(drive => (
                <button
                  key={drive.value}
                  className={`drive-type-option ${config.driveType === drive.value ? 'selected' : ''}`}
                  onClick={() => setConfig({ ...config, driveType: drive.value as any })}
                >
                  <div className="drive-type-label">{drive.label}</div>
                  <div className="drive-type-desc">{drive.description}</div>
                </button>
              ))}
            </div>
          </div>

          <div className="config-section">
            <div className="section-header">
              <h4>Subsystems</h4>
              <button onClick={addSubsystem} className="add-button">
                <Plus size={14} />
                Add Subsystem
              </button>
            </div>

            {config.subsystems.map((sub, index) => (
              <div key={index} className="subsystem-item">
                <div className="subsystem-header">
                  <input
                    type="text"
                    value={sub.name}
                    onChange={(e) => updateSubsystem(index, { name: e.target.value })}
                    placeholder="subsystem name"
                    className="subsystem-name"
                  />
                  <button
                    onClick={() => removeSubsystem(index)}
                    className="remove-button"
                  >
                    <Trash2 size={14} />
                  </button>
                </div>

                <div className="subsystem-config">
                  <select
                    value={sub.type}
                    onChange={(e) => updateSubsystem(index, { type: e.target.value as any })}
                  >
                    {SUBSYSTEM_TYPES.map(type => (
                      <option key={type.value} value={type.value}>
                        {type.icon} {type.label}
                      </option>
                    ))}
                  </select>

                  <label>
                    Motors:
                    <input
                      type="number"
                      min="0"
                      max="8"
                      value={sub.motors}
                      onChange={(e) => updateSubsystem(index, { motors: parseInt(e.target.value) })}
                    />
                  </label>
                </div>
              </div>
            ))}
          </div>

          <button onClick={generateCode} className="generate-button">
            <Download size={16} />
            Generate Configuration
          </button>
        </div>

        {generatedCode && (
          <div className="code-panel">
            <div className="code-header">
              <h4>Generated Code</h4>
              <button onClick={handleCopy} className="copy-button">
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? 'Copied!' : 'Copy'}
              </button>
            </div>
            <pre className="generated-code">
              <code>{generatedCode}</code>
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}